
import React, { useEffect, useState } from 'react';
import { KEYBOARD_MAP, MIDDLE_C } from '../constants.ts';
import { audioService } from '../services/audioService.ts';
import { KeyConfig } from '../types.ts';

interface PianoProps {
  onNotePlay: (midi: number) => void;
  onNoteStop?: (midi: number) => void;
  activeNotes: number[]; // Notes generated by system
  selectedNotes: number[]; // Notes currently held by user
  showLabels?: boolean;
  isDarkMode?: boolean;
}

const Piano: React.FC<PianoProps> = ({ onNotePlay, onNoteStop, selectedNotes, showLabels, isDarkMode }) => {
  const [pressedKeys, setPressedKeys] = useState<Set<number>>(new Set());

  const handleMouseDown = (midi: number) => {
    if (!pressedKeys.has(midi)) {
      audioService.startNote(midi);
      onNotePlay(midi);
      setPressedKeys(prev => new Set(prev).add(midi));
    }
  };

  const handleMouseUp = (midi: number) => {
    if (pressedKeys.has(midi)) {
      audioService.stopNote(midi);
      if (onNoteStop) onNoteStop(midi);
      setPressedKeys(prev => {
        const next = new Set(prev);
        next.delete(midi);
        return next;
      });
    }
  };

  useEffect(() => {
    const handleGlobalUp = () => {
      pressedKeys.forEach(midi => {
        audioService.stopNote(midi);
        if (onNoteStop) onNoteStop(midi);
      });
      setPressedKeys(new Set());
    };
    window.addEventListener('mouseup', handleGlobalUp);
    return () => window.removeEventListener('mouseup', handleGlobalUp);
  }, [pressedKeys, onNoteStop]);
  
  const whiteKeys = KEYBOARD_MAP.filter(k => k.type === 'white');
  const blackKeys = KEYBOARD_MAP.filter(k => k.type === 'black');

  const wkWidth = 100 / whiteKeys.length;

  return (
    // Removed overflow-x-auto to prevent scrolling
    <div className="w-full pb-4">
      {/* 
        Piano Container
        In Light Mode: Slightly lighter body but still dark enough to look like a piano.
        In Dark Mode: Slate 800
      */}
      <div className="relative h-48 md:h-64 bg-slate-800 dark:bg-slate-800 rounded-lg overflow-hidden select-none shadow-2xl border-t-8 border-slate-900 dark:border-slate-900 w-full ring-4 ring-slate-200 dark:ring-transparent">
        
        {/* White Keys Container */}
        <div className="flex w-full h-full">
          {whiteKeys.map((key) => {
              const isSelected = selectedNotes.includes(key.midi);
              const isPressed = pressedKeys.has(key.midi);
              
              return (
                <div
                  key={key.midi}
                  onMouseDown={() => handleMouseDown(key.midi)}
                  onMouseEnter={(e) => { if(e.buttons === 1) handleMouseDown(key.midi) }}
                  onMouseLeave={() => handleMouseUp(key.midi)}
                  className={`
                    relative h-full border-r border-slate-300 last:border-r-0 z-10 cursor-pointer
                    transition-colors duration-75
                    ${isSelected ? 'bg-blue-300' : isPressed ? 'bg-gray-200' : 'bg-white'}
                    active:bg-gray-300
                    rounded-b-md
                  `}
                  style={{ width: `${wkWidth}%` }}
                >
                  {key.midi === MIDDLE_C && (
                    <div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-xs text-slate-400 font-bold">C4</div>
                  )}
                </div>
              );
          })}
        </div>

        {/* Black Keys Container (Overlay) */}
        <div className="absolute top-0 left-0 w-full h-3/5 pointer-events-none">
           {blackKeys.map((key) => {
              const previousWhiteIndex = whiteKeys.findIndex(wk => wk.midi === key.midi - 1);
              if (previousWhiteIndex === -1) return null;

              const leftPercent = (previousWhiteIndex + 1) * wkWidth - (wkWidth * 0.3); // roughly centered on border

              const isSelected = selectedNotes.includes(key.midi);
              const isPressed = pressedKeys.has(key.midi);

              return (
                <div
                  key={key.midi}
                  className="absolute h-full pointer-events-auto z-20"
                  style={{ 
                    left: `${leftPercent}%`, 
                    width: `${wkWidth * 0.6}%` 
                  }}
                >
                  <div 
                    onMouseDown={() => handleMouseDown(key.midi)}
                    onMouseEnter={(e) => { if(e.buttons === 1) handleMouseDown(key.midi) }}
                    onMouseLeave={() => handleMouseUp(key.midi)}
                    className={`
                      w-full h-full rounded-b-md cursor-pointer border-x border-b border-black shadow-md
                      transition-colors duration-75
                      ${isSelected ? 'bg-blue-600' : isPressed ? 'bg-slate-700' : 'bg-piano-black'}
                    `}
                  />
                </div>
              );
           })}
        </div>
      </div>
    </div>
  );
};

export default Piano;
